### ISSUE TITLE
No provider for Apollo

### ISSUE THREAD

**Issue by IbrahimMemediPXL** [asotog/scully-strapi-tutorial#1]
**Thanks for sharing your project**

With the explanations posted at https://strapi.io/blog/how-to-build-a-jamstack-app-with-scully-io, I was able to quickly find my way around. But after 3 attempts I still have the same error. Do you know maybe, how I can solve it?

`
ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(AppModule)[PostsService -> BlogSamplesGQL -> Apollo -> Apollo -> Apollo]: 
  NullInjectorError: No provider for Apollo!
NullInjectorError: R3InjectorError(AppModule)[PostsService -> BlogSamplesGQL -> Apollo -> Apollo -> Apollo]: 
  NullInjectorError: No provider for Apollo!
    at NullInjector.get (core.mjs:11145:1)
    at R3Injector.get (core.mjs:11312:1)
    at R3Injector.get (core.mjs:11312:1)
    at R3Injector.get (core.mjs:11312:1)
    at injectInjectorOnly (core.mjs:4765:1)
    at Module.ɵɵinject (core.mjs:4769:1)
    at Object.BlogSamplesGQL_Factory [as factory] (graphql.gen.ts:854:30)
    at R3Injector.hydrate (core.mjs:11482:1)
    at R3Injector.get (core.mjs:11301:1)
    at injectInjectorOnly (core.mjs:4765:1)
    at resolvePromise (zone.js:1211:1)
    at resolvePromise (zone.js:1165:1)
    at zone.js:1278:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at TaskTrackingZoneSpec.onInvokeTask (task-tracking.js:73:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Object.onInvokeTask (core.mjs:25579:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:585:1)
`

_Thanks_

**Comment by IbrahimMemediPXL** [comment]
**I was able to find the solution.** 

> When you get the **ApolloModule** within the imports of _app.module.ts_ it works perfectly. 

The **queries** are outdated though, from the **Strapi V4** onwards you need to use instead of. 
```
query BlogSamples {
  blogSamples {
    id
    Title
    created_at
  }
}
```
Use this from now on
```
query BlogSamples {
  blogSamples {
    data {
      id
      attributes {
        Title
        createdAt
      }
    }
  }
}
```

There are still things that can be adjusted, since it has not been worked on for almost 1 year. If you need any help, you can always contact me on LinkedIn "Ibrahim Memedi".

**Comment by asotog** [comment]
hey @IbrahimMemediPXL  thanks for the input, yeah its been a while for those dependencies, we can check
